# =====================================
# Build stage
# =====================================
FROM node:20-alpine AS build-stage

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build


# =====================================
# Production stage
# =====================================
FROM node:20-alpine AS production-stage

WORKDIR /app
COPY --from=build-stage /app ./

ENV NODE_ENV=production
EXPOSE 3000
CMD ["yarn", "start"]
