# =====================================
# Build stage
# =====================================
FROM node:20-alpine AS build-stage

WORKDIR /app

# Copy ONLY yarn files
COPY package.json yarn.lock ./

# Configure yarn for docker network reliability
RUN yarn config set registry https://registry.npmjs.org \
    && yarn config set network-timeout 600000 -g \
    && yarn install --frozen-lockfile

# Copy app source
COPY . .

# Build
RUN yarn build


# =====================================
# Production stage
# =====================================
FROM node:20-alpine AS production-stage

WORKDIR /app

COPY --from=build-stage /app ./

ENV NODE_ENV=production

EXPOSE 3000

CMD ["yarn", "start"]
