# =====================================
# Build stage
# =====================================
FROM node:20 AS build-stage

WORKDIR /app
COPY package.json package-lock.json* ./
RUN yarn install

COPY . .
RUN yarn build

# =====================================
# Production stage
# =====================================
FROM node:20 AS production-stage

WORKDIR /app
COPY --from=build-stage /app ./

ENV NODE_ENV=production
EXPOSE 3000
CMD ["yarn", "start"]
