services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: finna-admin-frontend
    restart: always
    environment:
      VIRTUAL_HOST: admin.finna-entreprise.com
      LETSENCRYPT_HOST: admin.finna-entreprise.com
      LETSENCRYPT_EMAIL: gedeonyalakuhanda@gmail.com
    expose:
      - "3001"
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
