import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./theme-config.css";

import NextSessionProvider from "@/providers/NextSessionProvider";
import QueryProvider from "@/providers/QueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <NextSessionProvider>
          <QueryProvider>
            <ReduxProvider>
              <Theme>
                <main className="bg-[#f9fafb]">{children}</main>
              </Theme>
            </ReduxProvider>
          </QueryProvider>
        </NextSessionProvider>
      </body>
    </html>
  );
}
