import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./theme-config.css";

import NextSessionProvider from "@/providers/NextSessionProvider";
import QueryProvider from "@/providers/QueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Finna App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} antialiased`}>
      <body className={`${montserrat.variable} antialiased`}>
        <NextSessionProvider>
          <QueryProvider>
            <ReduxProvider>
              <Theme>
                <main className="bg-[#f9fafb]">{children}</main>
              </Theme>
              <Toaster
                position="bottom-center"
                toastOptions={{
                  style: {
                    fontFamily: "Montserrat, sans-serif",
                  },
                }}
              />
            </ReduxProvider>
          </QueryProvider>
        </NextSessionProvider>
      </body>
    </html>
  );
}

// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViZjMwYjViLWNlNTAtNDc3Yy05Nzg1LTczOThkMTY2ODVhYyIsImZ1bGxOYW1lIjoianVsaWVuIGJhbHVtZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlkQ2FyZENvcHkiOm51bGwsImlkQ2FyZE51bWJlciI6bnVsbCwiZW1haWxBZGRyZXNzIjoianVsaWVuYmFsdW1lYndlbmdlQGdtYWlsLmNvbSIsInBob25lIjoiKzI0MzgzNTEwMjQzNCIsInBhc3N3b3JkIjoiJGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTMscD00JGFTdm5acXQ0TmR4ZTNqenJjcHBCSEEkK0JBVnl2Q0RvM0RGVm43UzBjTGl3Zk9MWmN0QWwzbzZsNEYwVmt1eXhRayIsInJlZnJlc2hUb2tlbiI6IiRhcmdvbjJpZCR2PTE5JG09NjU1MzYsdD0zLHA9NCRkMDR4ckpva2Q0QjRyRHBNdXIvM09nJGp0UzdoUFZUM3dNSnZXeHIwN3BGZHk3M1M0V1NrRkt5U05xVEw1cnpWMlkiLCJjcmVhdGVkQXQiOiIyMDI1LTEyLTE4VDEyOjUzOjMyLjQ0NloiLCJ1cGRhdGVkQXQiOiIyMDI2LTAxLTIwVDIwOjUwOjAyLjY1NVoiLCJzaG9wQWZmZWN0YXRpb25zIjpbeyJyb2xlIjoiU1VQRVJfTUFSS0VUX0FETUlOIiwidXNlcklkIjoiZWJmMzBiNWItY2U1MC00NzdjLTk3ODUtNzM5OGQxNjY4NWFjIiwic2hvcElkIjoiNDM1OTlmYjItMmIzYy00MDc1LTg1MzEtOGM2Y2NkYzBhNWQxIiwiaXNBY3RpdmUiOnRydWUsInNob3AiOnsiaWQiOiI0MzU5OWZiMi0yYjNjLTQwNzUtODUzMS04YzZjY2RjMGE1ZDEiLCJuYW1lIjoiRmlubmEiLCJhZGRyZXNzIjpudWxsLCJuYXRpb25hbElkIjpudWxsLCJyY2NtIjpudWxsLCJlbWFpbEFkZHJlc3MiOm51bGwsInBob25lIjoiKzI0MzgzNTEwMjQzNCIsImNyZWF0b3JJZCI6ImViZjMwYjViLWNlNTAtNDc3Yy05Nzg1LTczOThkMTY2ODVhYyIsInBlcmNlbnRhZ2UiOjAsInR5cGVJZCI6IjhjZTQxNGQyLTEzOWItNDBiYy04YmE2LTMzYWRiODM1YzVmNSIsImNvZGUiOiIxNzMyNjkiLCJjcmVhdGVkQXQiOiIyMDI2LTAxLTA3VDIxOjQ4OjU5LjA2M1oiLCJ1cGRhdGVkQXQiOiIyMDI2LTAxLTA3VDIxOjQ4OjU5LjA2M1oifX1dLCJpYXQiOjE3NzM4ODY2NzEsImV4cCI6MjA4OTQ2MjY3MX0.abJtenlF3pPLKx36j3DTwHMDL1g1GYAKNYE45-fitcQ