import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Montserrat } from "next/font/google";
import "./theme-config.css";

import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import QueryProvider from "@/providers/QueryProvider";
import NextSessionProvider from "@/providers/NextSessionProvider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <NextSessionProvider>
          <QueryProvider>
            <ReduxProvider>
              <Theme>
                <main className="bg-[#f9fafb] min-h-screen flex items-center justify-center">
                  {children}
                </main>
              </Theme>
            </ReduxProvider>
          </QueryProvider>
        </NextSessionProvider>
      </body>
    </html>
  );
}
